@startuml C3RequestC2C1
== Peers HandShake ==
Peer1 -> Server: get_peers_list()
Server --> Peer1: available_peers_list()
Peer2 -> Server: get_peers_list()
Server --> Peer2: available_peers_list()
Peer2 -> Peer1: establist_link()
Peer3 -> Server: get_peers_list()
Server --> Peer3: available_peers_list()
Peer3 -> Peer1: establist_link()
Peer3 -> Peer2: establist_link()
== Exchange BitField == 
Peer2 -> Peer1: Bitfield
Peer1 -> Peer2: Bitfield
Peer3 -> Peer1: Bitfield
Peer1 -> Peer3: Bitfield
Peer3 -> Peer2: Bitfield
Peer2 -> Peer3: Bitfield
== Peer Connections ==
Peer1 -> Peer2: Uninterested
note left: Peer Connection 1
Peer2 -> Peer1: Uninterested
Peer1 --> Peer2: Choke
Peer2 --> Peer1: Choke
== ... Concurrently ...==
Peer1 -> Peer3: Uninterested
note left: Peer Connection 2
Peer3 -> Peer1: Interested
Peer1 --> Peer3: UnChoke
Peer1 -> Peer1: Waiting Request
Peer3 -> Peer1: Request Piece
Peer1 --> Peer3: Send Piece
... Repeatly Request and Send ...
Peer3 -> Peer1: UnInterested
Peer1 --> Peer3: Choke
== ... Concurrently ...==
Peer2 -> Peer3: Uninterested
note left: Peer Connection 3
Peer3 -> Peer2: Interested
Peer2 --> Peer3: UnChoke
Peer2 -> Peer2: Waiting Request
Peer3 -> Peer2: Request Piece
Peer2 --> Peer3: Send Piece
... Repeatly Request and Send ...
Peer3 -> Peer2: UnInterested
Peer2 --> Peer3: Choke
@enduml