MARGIN = 40
LEFT_MARGIN = 20
TINY_MARGIN = 10

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 500

LABEL_HEIGHT = 50
LABEL_WIDTH = 40

WORD_OFFSET = 5

TEX_BOX_WIDTH = 100

LOG_LEFT_MARGIN = LEFT_MARGIN + LABEL_WIDTH + TEX_BOX_WIDTH +100
LOG_WIDTH = 500
LOG_HEIGH = WINDOW_HEIGHT - 2 * MARGIN

LOG_LABEL_LEFT_MARGIN = LOG_LEFT_MARGIN + LOG_WIDTH / 2

SUBMIT_BUTTON_TOP_MARGIN = MARGIN + 2 * LABEL_HEIGHT + TINY_MARGIN
SUBMIT_LEFT_MARGIN = LEFT_MARGIN + TEX_BOX_WIDTH

MAX_INT = 1e100